### ISSUE TITLE
스터디 내용이 안보이는 버그가 있습니다

### ISSUE THREAD

**Issue by xncbf** [jellysoo97/ma-javascript-study#1]
👀

**Comment by jellysoo97** [comment]
![KakaoTalk_Photo_2023-01-12-22-55-09](https://user-images.githubusercontent.com/91869170/212085141-0684509d-f112-41df-b604-a328e561a2c0.jpeg)

**Comment by djmin43** [comment]
이슈가 resolve되지 않는 버그가 있습니다

**Comment by xncbf** [comment]
🎉🥳

**Comment by djmin43** [comment]
🙇
